---
# default
default: -p capybara -p webkit

# drivers
capybara: -r features/support/env/capybara.rb
selenium: -r features/support/env/selenium.rb
watir: -r features/support/env/watir.rb

# browser
webkit: BROWSER=webkit
poltergeist: BROWSER=poltergeist
firefox: BROWSER=firefox
chrome: BROWSER=chrome
safari: BROWSER=safari
phantomjs: BROWSER=phantomjs
